### ISSUE TITLE
Customer Model

### ISSUE THREAD

**Issue by NicoleAtBmc** [spiresystems/spire-js#1]
I'm not sure if anyone looks at these!! But I'll submit anyway - the Customer Model info in Docs says there is an element called shippingAddresses but that is not being returned with the model...

**Comment by mattkalina** [comment]
It appears the `shippingAddresses` attribute has been commented out on the customer model. I will look into it for you.

**Comment by NicoleAtBmc** [comment]
Great thank you

**Comment by NicoleAtBmc** [comment]
Question for you - I'm developing using this locally - if I'm using this (https://localhost:10880/api/v1/companies/inspire_health_2_6/customers/) to preview what should be coming through to my app, do I have to reinstall the Spire Server on my local machine in order for me to see your updates?

**Comment by mattkalina** [comment]
No you do not need to reinstall Spire Server but you do need to update the spire-js package. From your project directory:

```
npm update spire-js
```

**Comment by NicoleAtBmc** [comment]
perfect, thanks!
